// Code generated by conduit at 2025-09-14 09:43:09. DO NOT EDIT.
// Source: __conduit/health

package health_gen

import (
	"net/http"

	original "my-app/__conduit/health"
)

// GetGETHandler returns the GET handler for this route
func GetGETHandler() http.HandlerFunc {
	return original.GET
}

// GetGETRoute returns the route pattern for GET method
func GetGETRoute() string {
	return "__conduit/health"
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Methods:    GetRouteMethods(),
		Parameters: []string{  },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}