// Code generated by conduit at 2025-09-15 08:34:27. DO NOT EDIT.
// Source: __conduit/health

package health_gen

import (
	"net/http"
	
	
	
	"github.com/tristendillon/conduit/core/version"
	
	
	
)

// GET - Generated from original source
func GET(w http.ResponseWriter, r *http.Request) {
w.WriteHeader(http.StatusOK)
  w.Write([]byte(version.Version))
}

// SetupRoutes registers all handlers for this route with the provided mux
func SetupRoutes(mux *http.ServeMux, basePath string) {
	
	mux.HandleFunc("GET "+basePath, GET)
	
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Methods:    GetRouteMethods(),
		Parameters: []string{  },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}