// Code generated by conduit at 2025-09-14 10:31:35. DO NOT EDIT.
// Source: __conduit/health

package health_gen

import (
	"net/http"

	"github.com/tristendillon/conduit/core/version"
)

func GET(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte(version.Version))
}

func SetupRoutes(mux *http.ServeMux, basePath string) {

	mux.HandleFunc("GET "+basePath, GET)

}

func GetRouteMethods() []string {
	return []string{"GET"}
}

func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Methods:    GetRouteMethods(),
		Parameters: []string{},
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}
