// Code generated by conduit at 2025-09-15 08:34:27. DO NOT EDIT.
// Source: api/v1/profiles

package profiles_gen

import (
	"net/http"
	
	
	"encoding/json"
	
	
	
	
	"my-app/.conduit/go/dependencies/api/v1/profiles/profile_repo"
	
)

// GET - Generated from original source
func GET(w http.ResponseWriter, r *http.Request) {
w.WriteHeader(http.StatusOK)
	profiles := profile_repo.GetAllProfiles()
	data, err := json.Marshal(profiles)
	if err != nil {
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
	w.Write(data)
}

// SetupRoutes registers all handlers for this route with the provided mux
func SetupRoutes(mux *http.ServeMux, basePath string) {
	
	mux.HandleFunc("GET "+basePath, GET)
	
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Methods:    GetRouteMethods(),
		Parameters: []string{  },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}