// Code generated by conduit at 2025-09-14 10:31:35. DO NOT EDIT.
// Source: api/v1/users/id_

package id__gen

import (
	"net/http"
	
	"encoding/json"
	
	"my-app/api/v1/users/user_repo"
	
)

func GET(w http.ResponseWriter, r *http.Request) {
id := r.URL.Query().Get("id")
	user := user_repo.FindUser(id)
	if user == nil {
		http.Error(w, "User not found", http.StatusNotFound)
		return
	}
	data, err := json.Marshal(user)
	if err != nil {
		http.Error(w, "Internal Server Error", http.StatusInternalServerError)
		return
	}
	w.WriteHeader(http.StatusOK)
	w.Write(data)
}

func DELETE(w http.ResponseWriter, r *http.Request) {
id := r.URL.Query().Get("id")
	user := user_repo.DeleteUser(id)
	if user == -1 {
		http.Error(w, "User not found", http.StatusNotFound)
		return
	}
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("Successfully deleted user"))
}

func SetupRoutes(mux *http.ServeMux, basePath string) {
	
	mux.HandleFunc("GET "+basePath, GET)
	
	mux.HandleFunc("DELETE "+basePath, DELETE)
	
}

func GetRouteMethods() []string {
	return []string{ "GET", "DELETE" }
}

func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Methods:    GetRouteMethods(),
		Parameters: []string{ "id" },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}