// Code generated by conduit at 2025-09-14 09:43:09. DO NOT EDIT.
// Source: api/v1/users/id_

package id__gen

import (
	"net/http"

	original "my-app/api/v1/users/id_"
)

// GetGETHandler returns the GET handler for this route
func GetGETHandler() http.HandlerFunc {
	return original.GET
}

// GetGETRoute returns the route pattern for GET method
func GetGETRoute() string {
	return "api/v1/users/:id"
}

// GetDELETEHandler returns the DELETE handler for this route
func GetDELETEHandler() http.HandlerFunc {
	return original.DELETE
}

// GetDELETERoute returns the route pattern for DELETE method
func GetDELETERoute() string {
	return "api/v1/users/:id"
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET", "DELETE" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Methods:    GetRouteMethods(),
		Parameters: []string{ "id" },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}