// Code generated by conduit. DO NOT EDIT.

package generated

import (
	"github.com/tristendillon/conduit/core/models"
)

func GetRouteTree() *models.RouteTree {
	tree := models.NewRouteTree()
	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: __conduit/health
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
		RelPath:     "__conduit/health",
		PackageName: "health",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
		RelPath:     "api/v1/profiles",
		PackageName: "profiles",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/profiles/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
		RelPath:     "api/v1/profiles/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})

	// Route: api/v1/users
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
		RelPath:     "api/v1/users",
		PackageName: "users",
		Methods:     []string{"GET" },
	})

	// Route: api/v1/users/:id
	tree.AddRoute(&models.ParsedFile{
		Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
		RelPath:     "api/v1/users/id_",
		PackageName: "id_",
		Methods:     []string{"GET", "DELETE" },
	})


	return tree
}

func GetRoutes() []models.Route {
	return []models.Route{
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "__conduit/health",
			FolderPath: "__conduit/health",
			Segments: []models.RouteSegment{
				{
					Name:      "__conduit",
					APIName:   "__conduit",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "health",
					APIName:   "health",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     true,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/__conduit/health/route.go",
				RelPath:     "__conduit/health",
				PackageName: "health",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles",
			FolderPath: "api/v1/profiles",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/route.go",
				RelPath:     "api/v1/profiles",
				PackageName: "profiles",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/profiles/:id",
			FolderPath: "api/v1/profiles/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "profiles",
					APIName:   "profiles",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/profiles/id_/route.go",
				RelPath:     "api/v1/profiles/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
		{
			APIPath:    "api/v1/users",
			FolderPath: "api/v1/users",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
			},
			Parameters: []string{ },
			IsLeaf:     false,
			Methods:    []string{"GET" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/route.go",
				RelPath:     "api/v1/users",
				PackageName: "users",
				Methods:     []string{"GET" },
			},
		},
		{
			APIPath:    "api/v1/users/:id",
			FolderPath: "api/v1/users/id_",
			Segments: []models.RouteSegment{
				{
					Name:      "api",
					APIName:   "api",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "v1",
					APIName:   "v1",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "users",
					APIName:   "users",
					IsParam:   false,
					ParamName: "",
				},
				{
					Name:      "id_",
					APIName:   ":id",
					IsParam:   true,
					ParamName: "id",
				},
			},
			Parameters: []string{"id" },
			IsLeaf:     true,
			Methods:    []string{"GET", "DELETE" },
			ParsedFile: &models.ParsedFile{
				Path:        "/workspaces/conduit/my-app/api/v1/users/id_/route.go",
				RelPath:     "api/v1/users/id_",
				PackageName: "id_",
				Methods:     []string{"GET", "DELETE" },
			},
		},
	}
}

var routeMap = map[string]*models.Route{
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"__conduit/health": &models.Route{
		APIPath:    "__conduit/health",
		FolderPath: "__conduit/health",
		Parameters: []string{ },
		IsLeaf:     true,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles": &models.Route{
		APIPath:    "api/v1/profiles",
		FolderPath: "api/v1/profiles",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/profiles/:id": &models.Route{
		APIPath:    "api/v1/profiles/:id",
		FolderPath: "api/v1/profiles/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
	"api/v1/users": &models.Route{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Parameters: []string{ },
		IsLeaf:     false,
		Methods:    []string{"GET" },
	},
	"api/v1/users/:id": &models.Route{
		APIPath:    "api/v1/users/:id",
		FolderPath: "api/v1/users/id_",
		Parameters: []string{"id" },
		IsLeaf:     true,
		Methods:    []string{"GET", "DELETE" },
	},
}

func GetRouteByAPIPath(apiPath string) (*models.Route, bool) {
	route, exists := routeMap[apiPath]
	return route, exists
}

func GetAllAPIPaths() []string {
	paths := make([]string, 0, len(routeMap))
	for path := range routeMap {
		paths = append(paths, path)
	}
	return paths
}