// Code generated by conduit at 2025-09-14 09:43:09. DO NOT EDIT.
// Source: api/v1/users

package users_gen

import (
	"net/http"

	original "my-app/api/v1/users"
)

// GetGETHandler returns the GET handler for this route
func GetGETHandler() http.HandlerFunc {
	return original.GET
}

// GetGETRoute returns the route pattern for GET method
func GetGETRoute() string {
	return "api/v1/users"
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "api/v1/users",
		FolderPath: "api/v1/users",
		Methods:    GetRouteMethods(),
		Parameters: []string{  },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}