// Code generated by conduit at 2025-09-15 09:00:01. DO NOT EDIT.
// Source: api/v1/orgs

package orgs_gen

import (
	"net/http"
	
	
	
	
	
)

// GET - Generated from original source
func GET(w http.ResponseWriter, r *http.Request) {
w.WriteHeader(http.StatusOK)
	w.Write([]byte("Hello, World!"))
}

// SetupRoutes registers all handlers for this route with the provided mux
func SetupRoutes(mux *http.ServeMux, basePath string) {
	
	mux.HandleFunc("GET "+basePath, GET)
	
}

// GetRouteMethods returns all HTTP methods supported by this route
func GetRouteMethods() []string {
	return []string{ "GET" }
}

// GetRouteInfo returns metadata about this route
func GetRouteInfo() RouteInfo {
	return RouteInfo{
		APIPath:    "api/v1/orgs",
		FolderPath: "api/v1/orgs",
		Methods:    GetRouteMethods(),
		Parameters: []string{  },
	}
}

type RouteInfo struct {
	APIPath    string
	FolderPath string
	Methods    []string
	Parameters []string
}